@startuml
'https://plantuml.com/activity-diagram-beta

|Player|
|System|
start
|Player|
:Draw cards;
|Player|
:Program robot;
|System|
repeat
:Execute next step;

if (Damage done) then (true)
|Player|
:Deal damage cards;

else (false)

endif
|System|
if (Winner found) then (true)
stop
else (false)
endif
|System|
repeat while (Cards left?) is (true) not (false)

|Player|
:Buy upgrade;

stop

@enduml
