@startuml
'https://plantuml.com/activity-diagram-beta

|Player|
|System|
start
repeat
:Choose next player;
if (command is interactive) then (true)
|Player|
:choose command
    from options;
else (false)
|System|
endif
:     <<automatic>>
Execute command;

repeat while (More players?) is (true)
->false;
:Execute entities;


stop




@enduml
