@startuml
'https://plantuml.com/activity-diagram-beta


start
:int i=1;
repeat
:Choose player i;
if (command is interactive) then (true)
:choose command
    from options;
else (false)
endif
:     <<automatic>>
Execute command;
backward:i++;
repeat while (i < players.lenght) is (true)
->false;


stop




@enduml
