@startuml
'https://plantuml.com/class-diagram

Abstract BoardEntity {
Heading
}

Abstract DamageEntity {
doAction ()
}

Abstract PassivEntity

Abstract MovementEntity {
doAction()
}

Class Space {
Position
}

Class ProgrammingCard {
Command
}

Board "1" - "2..6" Robot
Board "1" -- "64..*" Space
Space "0..1" -- "0..1" Robot
Robot "1" -- "3..8" ProgrammingCard : < Belongs to
Robot "1" -- "1"PlayerMat : < Belongs to
PlayerMat "1" *--"5" ProgrammingField
Space "0..1" --- "0...5" BoardEntity : < Is placed on
BoardEntity <|-- DamageEntity
DamageEntity <|-- BoardLaser
BoardEntity <|-- PassivEntity
PassivEntity <|-- Wall
PassivEntity <|-- "6" CheckPoint
BoardEntity <|-- MovementEntity
MovementEntity <|-- Gear
MovementEntity <|-- ConveyorBelt
MovementEntity <|-- PushPanel

@enduml